default: &default
  adapter: postgresql
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: bestow_bootstrap

# test:
#   <<: *default
#   database: bestow_bootstrap

# integration_test:
#   <<: *default
#   database: bestow_bootstrap

production:
  <<: *default
  database: bestow_bootstrap